- name: create data dir & config dir
  become: true
  become_user: root
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
    recurse: yes
  with_items:
    - "{{ dash_data_dir }}"
    - "{{ dash_conf_dir }}"

- name: put dash config file
  become: true
  become_user: root
  template:
    src: "dash.conf.j2"
    dest: "{{ dash_conf_dir }}/dash.conf"
  notify: restart dash
